#!/bin/bash
# generated by amber transpiler
set -e


__amber_rt_gp03lq81h9k8_to_string() {
    local val=$1
    local tag=${val%%:*}
    local data=${val#*:}
    case $tag in
        arr)
            local arr_name=$data
            local -n items=$arr_name
            local result="["
            local first=true
            for i in "${!items[@]}"; do
                if [ "$first" = true ]; then
                    first=false
                else
                    result+=", "
                fi
                result+="$(__amber_rt_gp03lq81h9k8_to_string "${items[$i]}")"
            done
            result+="]"
            echo "$result"
            ;;
        bool)
            if [ "$data" = "0" ]; then echo "true"; else echo "false"; fi
            ;;
        *)
            echo "$data"
            ;;
    esac
}

# --- module: io (core:io) ---
# --- end module: io ---


# --- module: str (core:str) ---
# --- end module: str ---


# --- module: utils (local:utils) ---
__amber_mod_gp03lq81h9k8_utils_something() {
    local __amber_tmp_gp03lq81h9k8_0
    __amber_tmp_gp03lq81h9k8_0="str:Hi You"
    local __amber_mod_gp03lq81h9k8_utils_param1
    __amber_mod_gp03lq81h9k8_utils_param1="${1:-$__amber_tmp_gp03lq81h9k8_0}"
    echo "$(__amber_rt_gp03lq81h9k8_to_string "$__amber_mod_gp03lq81h9k8_utils_param1")"
    local __amber_tmp_gp03lq81h9k8_1
    __amber_tmp_gp03lq81h9k8_1="str:oo"
    __amber_ret_gp03lq81h9k8___amber_mod_gp03lq81h9k8_utils_something="$__amber_tmp_gp03lq81h9k8_1"
    return 0
}

__amber_mod_gp03lq81h9k8_utils_my_func() {
    local __amber_tmp_gp03lq81h9k8_2
    __amber_tmp_gp03lq81h9k8_2="str:my funt"
    echo "$(__amber_rt_gp03lq81h9k8_to_string "$__amber_tmp_gp03lq81h9k8_2")"
}

# --- end module: utils ---

__amber_tmp_gp03lq81h9k8_3="num:69.0"
echo "$(__amber_rt_gp03lq81h9k8_to_string "$__amber_tmp_gp03lq81h9k8_3")"
__amber_tmp_gp03lq81h9k8_4="num:44.0"
__amber_tmp_gp03lq81h9k8_5="str:$(__amber_rt_gp03lq81h9k8_to_string "$__amber_tmp_gp03lq81h9k8_4")"
echo "$(__amber_rt_gp03lq81h9k8_to_string "$__amber_tmp_gp03lq81h9k8_5")"
__amber_tmp_gp03lq81h9k8_6="str:Call from simple"
__amber_mod_gp03lq81h9k8_utils_something "$__amber_tmp_gp03lq81h9k8_6"
__amber_tmp_gp03lq81h9k8_7="$__amber_ret_gp03lq81h9k8___amber_mod_gp03lq81h9k8_utils_something"
__amber_mod_gp03lq81h9k8_utils_my_func
__amber_tmp_gp03lq81h9k8_8="$__amber_ret_gp03lq81h9k8___amber_mod_gp03lq81h9k8_utils_my_func"
