#!/bin/bash
# generated by amber transpiler
set -e


__amber_rt_1aatgqu4jgfyi_to_string() {
    local val=$1
    local tag=${val%%:*}
    local data=${val#*:}
    case $tag in
        arr)
            local arr_name=$data
            local -n items=$arr_name
            local result="["
            local first=true
            for i in "${!items[@]}"; do
                if [ "$first" = true ]; then
                    first=false
                else
                    result+=", "
                fi
                result+="$(__amber_rt_1aatgqu4jgfyi_to_string "${items[$i]}")"
            done
            result+="]"
            echo "$result"
            ;;
        bool)
            if [ "$data" = "0" ]; then echo "true"; else echo "false"; fi
            ;;
        *)
            echo "$data"
            ;;
    esac
}

# --- module: io (core:io) ---
# --- end module: io ---

__amber_your_name() {
    local __amber_tmp_1aatgqu4jgfyi_0
    __amber_tmp_1aatgqu4jgfyi_0="str:Yoo"
    __amber_ret_1aatgqu4jgfyi___amber_your_name="err:${__amber_tmp_1aatgqu4jgfyi_0#*:}"
    return 0
    local __amber_tmp_1aatgqu4jgfyi_1
    __amber_tmp_1aatgqu4jgfyi_1="str:Name"
    __amber_ret_1aatgqu4jgfyi___amber_your_name="$__amber_tmp_1aatgqu4jgfyi_1"
    return 0
}

__amber_your_name
__amber_tmp_1aatgqu4jgfyi_2="$__amber_ret_1aatgqu4jgfyi___amber_your_name"
if [[ "$__amber_tmp_1aatgqu4jgfyi_2" == err:* ]]; then
    __amber__="${__amber_tmp_1aatgqu4jgfyi_2#*:}"
    __amber_tmp_1aatgqu4jgfyi_4="str:First"
    echo "$(__amber_rt_1aatgqu4jgfyi_to_string "$__amber_tmp_1aatgqu4jgfyi_4")"
        __amber_tmp_1aatgqu4jgfyi_5="str:Got"
__amber_tmp_1aatgqu4jgfyi_3="$__amber_tmp_1aatgqu4jgfyi_5"
else
    __amber_tmp_1aatgqu4jgfyi_3="$__amber_tmp_1aatgqu4jgfyi_2"
fi
echo "$(__amber_rt_1aatgqu4jgfyi_to_string "$__amber_tmp_1aatgqu4jgfyi_3")"
