/*
 * Generated by Amber Compiler
 * Entry: /home/kys0adam/IdeaProjects/amber-lang/amber-scripts/simple_project/simple.amb
 * Optimization: O1
 * GC: BOEHM
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include <stdint.h>
#include <gc.h>

typedef struct {
    const char* name;
    int32_t id;
    const char** variants;
    int variant_count;
} __amber_type_t;

typedef struct {
    __amber_type_t* type;
} __amber_header_t;

typedef struct {
    __amber_header_t header;
    double value;
} __amber_box_double_t;

typedef struct {
    __amber_header_t header;
    int value;
} __amber_box_bool_t;

typedef struct {
    __amber_header_t header;
    char* value;
} __amber_box_string_t;

typedef struct {
    __amber_header_t header;
    int value;
} __amber_box_enum_t;

typedef struct {
    __amber_header_t header;
    void** data;
    int32_t length;
    int32_t capacity;
} __amber_list_t;

struct AMBER_RESULT {
    void* value;
    int32_t has_error;
    const char* error_message;
};

static struct AMBER_RESULT __amber_rt_last_error = { NULL, 0, NULL };

extern __amber_type_t __amber_type_double;
extern __amber_type_t __amber_type_string;
extern __amber_type_t __amber_type_bool;
extern __amber_type_t __amber_type_list;

char* __amber_rt_to_string(void* val);
char* __amber_rt_str_concat(const char* s1, const char* s2);

static inline void* __amber_rt_alloc(size_t size) {
    void* ptr = GC_MALLOC(size);
    if (!ptr) { fprintf(stderr, "Out of memory\n"); exit(1); }
    return ptr;
}

static inline struct AMBER_RESULT __amber_rt_result_success(void* val) {
    struct AMBER_RESULT res = { val, 0, NULL };
    return res;
}

static inline struct AMBER_RESULT __amber_rt_result_error(const char* msg) {
    struct AMBER_RESULT res = { NULL, 1, msg };
    __amber_rt_last_error = res;
    return res;
}

static inline void* __amber_rt_box_double(double d) {
    __amber_box_double_t* p = (__amber_box_double_t*)__amber_rt_alloc(sizeof(__amber_box_double_t));
    p->header.type = &__amber_type_double;
    p->value = d;
    return p;
}

static inline double __amber_rt_unbox_double(void* p) {
    if (!p) return 0.0;
    return ((__amber_box_double_t*)p)->value;
}

static inline void* __amber_rt_box_bool(int b) {
    __amber_box_bool_t* p = (__amber_box_bool_t*)__amber_rt_alloc(sizeof(__amber_box_bool_t));
    p->header.type = &__amber_type_bool;
    p->value = b;
    return p;
}

static inline int __amber_rt_unbox_bool(void* p) {
    if (!p) return 0;
    return ((__amber_box_bool_t*)p)->value;
}

static inline void* __amber_rt_box_string(char* s) {
    __amber_box_string_t* p = (__amber_box_string_t*)__amber_rt_alloc(sizeof(__amber_box_string_t));
    p->header.type = &__amber_type_string;
    p->value = s;
    return p;
}

static inline char* __amber_rt_unbox_string(void* p) {
    if (!p) return "";
    __amber_header_t* h = (__amber_header_t*)p;
    if (h->type == &__amber_type_string) {
        return ((__amber_box_string_t*)p)->value;
    }
    return (char*)p;
}

static inline void* __amber_rt_box_enum(int value, __amber_type_t* type) {
    __amber_box_enum_t* p = (__amber_box_enum_t*)__amber_rt_alloc(sizeof(__amber_box_enum_t));
    p->header.type = type;
    p->value = value;
    return p;
}

static inline int __amber_rt_unbox_enum(void* p) {
    if (!p) return 0;
    return ((__amber_box_enum_t*)p)->value;
}

static inline int __amber_rt_is_error(struct AMBER_RESULT res) {
    return res.has_error;
}

static inline void* __amber_rt_unwrap(struct AMBER_RESULT res) {
    return res.value;
}

static inline int __amber_rt_is_type(void* obj, __amber_type_t* type) {
    if (!obj) return 0;
    __amber_header_t* header = (__amber_header_t*)obj;
    return header->type == type;
}

static inline void* __amber_rt_as_type(void* obj, __amber_type_t* type) {
    if (__amber_rt_is_type(obj, type)) return obj;
    // We'll call the intrinsic panic if available, or a simple version here
    fprintf(stderr, "ClassCastException: object is not of type %s\n", type->name);
    exit(1);
    return NULL;
}

void __amber_rt_print(const void* val) {
    if (val) printf("%s", __amber_rt_to_string((void*)val));
}

void __amber_rt_println(const void* val) {
    if (val) printf("%s\n", __amber_rt_to_string((void*)val));
    else printf("\n");
}

char* __amber_rt_readln() {
    char* buf = (char*)__amber_rt_alloc(1024);
    if (fgets(buf, 1024, stdin)) {
        size_t len = strlen(buf);
        if (len > 0 && buf[len-1] == '\n') buf[len-1] = '\0';
        return buf;
    }
    return "";
}

double __amber_rt_str_len(const char* s) {
    return (double)(s ? strlen(s) : 0);
}

char* __amber_rt_from_num(double n) {
    char* buf = (char*)__amber_rt_alloc(64);
    snprintf(buf, 64, "%g", n);
    return buf;
}

int __amber_rt_str_contains(const char* s, const char* sub) { return (s && sub && strstr(s, sub)) ? 1 : 0; }

int __amber_rt_str_starts_with(const char* s, const char* sub) { return (s && sub && strncmp(s, sub, strlen(sub)) == 0) ? 1 : 0; }

int __amber_rt_str_ends_with(const char* s, const char* sub) {
    if (!s || !sub) return 0;
    size_t len = strlen(s);
    size_t sublen = strlen(sub);
    if (sublen > len) return 0;
    return strcmp(s + len - sublen, sub) == 0 ? 1 : 0;
}

double __amber_rt_math_abs(double n) { return fabs(n); }

double __amber_rt_math_sqrt(double n) { return sqrt(n); }

double __amber_rt_math_pow(double b, double e) { return pow(b, e); }

double __amber_rt_math_sin(double n) { return sin(n); }

double __amber_rt_math_cos(double n) { return cos(n); }

double __amber_rt_math_floor(double n) { return floor(n); }

double __amber_rt_math_ceil(double n) { return ceil(n); }

double __amber_rt_math_max(double a, double b) { return a > b ? a : b; }

double __amber_rt_math_min(double a, double b) { return a < b ? a : b; }

void __amber_rt_exit(double code) { exit((int)code); }

void __amber_rt_panic(const char* msg) {
    fprintf(stderr, "panic: %s\n", msg);
    exit(1);
}

double __amber_rt_list_len(__amber_list_t* l) { return l ? (double)l->length : 0.0; }

void __amber_rt_list_push(__amber_list_t* l, void* val) {
    if (!l) return;
    if (l->length >= l->capacity) {
        l->capacity = l->capacity == 0 ? 4 : l->capacity * 2;
        void** new_data = (void**)__amber_rt_alloc(sizeof(void*) * l->capacity);
        if (l->data) memcpy(new_data, l->data, sizeof(void*) * l->length);
        l->data = new_data;
    }
    l->data[l->length++] = val;
}

void* __amber_rt_list_pop(__amber_list_t* l) {
    if (!l || l->length == 0) return NULL;
    return l->data[--l->length];
}

void* __amber_rt_list_get(__amber_list_t* l, double idx) {
    int i = (int)idx;
    if (!l || i < 0 || i >= l->length) return NULL;
    return l->data[i];
}

char* __amber_rt_to_string(void* val) {
    if (!val) return "null";
    __amber_header_t* h = (__amber_header_t*)val;
    if (h->type == &__amber_type_double) {
        return __amber_rt_from_num(__amber_rt_unbox_double(val));
    }
    if (h->type == &__amber_type_bool) {
        return __amber_rt_unbox_bool(val) ? "true" : "false";
    }
    if (h->type == &__amber_type_string) {
        return __amber_rt_unbox_string(val);
    }
    if (h->type->variant_count > 0) {
        __amber_box_enum_t* e = (__amber_box_enum_t*)val;
        if (e->value >= 0 && e->value < h->type->variant_count) {
            return (char*)h->type->variants[e->value];
        }
    }
    if (h->type == &__amber_type_list) {
        __amber_list_t* l = (__amber_list_t*)val;
        char* res = "[";
        for (int i = 0; i < l->length; i++) {
            res = __amber_rt_str_concat(res, __amber_rt_to_string(l->data[i]));
            if (i < l->length - 1) res = __amber_rt_str_concat(res, ", ");
        }
        res = __amber_rt_str_concat(res, "]");
        return res;
    }
    return (char*)val;
}

char* __amber_rt_str_concat(const char* s1, const char* s2) {
    if (!s1) return (char*)s2;
    if (!s2) return (char*)s1;
    size_t len1 = strlen(s1);
    size_t len2 = strlen(s2);
    char* res = (char*)__amber_rt_alloc(len1 + len2 + 1);
    memcpy(res, s1, len1);
    memcpy(res + len1, s2, len2);
    res[len1 + len2] = '\0';
    return res;
}

#include <stdarg.h>
__amber_list_t* __amber_rt_create_list(int count, ...) {
    __amber_list_t* l = (__amber_list_t*)__amber_rt_alloc(sizeof(__amber_list_t));
    l->header.type = &__amber_type_list;
    l->length = count;
    l->capacity = count < 4 ? 4 : count;
    l->data = (void**)__amber_rt_alloc(sizeof(void*) * l->capacity);
    va_list args;
    va_start(args, count);
    for (int i = 0; i < count; i++) {
        l->data[i] = va_arg(args, void*);
    }
    va_end(args);
    return l;
}

__amber_type_t __amber_type_double = { "num", 1, NULL, 0 };
__amber_type_t __amber_type_string = { "string", 2, NULL, 0 };
__amber_type_t __amber_type_bool = { "bool", 3, NULL, 0 };
__amber_type_t __amber_type_list = { "list", 4, NULL, 0 };

const char* __am_variants_color[] = { "red", "green", "blue" };
typedef enum {
    __am_color_red,
    __am_color_green,
    __am_color_blue
} __am_color;
__amber_type_t __am_type_color = { "color", 94842823, __am_variants_color, 3 };
void __am_main();
void __am_check_type(void* __am_v);
int __am_is_color_blue(int __am_c);

void __am_main() {
int __am_c = __am_color_red    ;
__amber_list_t* __am_colors = __amber_rt_create_list(2, __amber_rt_box_enum(__am_color_red, &__am_type_color), __amber_rt_box_enum(__am_color_green, &__am_type_color))    ;
__amber_rt_println(__amber_rt_box_string(__amber_rt_str_concat("Current color: ", __amber_rt_to_string(__am_c))))    ;
__amber_rt_println(__amber_rt_box_string(__amber_rt_str_concat("All colors: ", __amber_rt_to_string(__am_colors))))    ;
__amber_rt_println(__amber_rt_box_string(__amber_rt_str_concat("Is blue: ", __amber_rt_to_string(__am_is_color_blue(__am_color_blue)))))    ;
__am_check_type(__amber_rt_box_enum(__am_color_blue, &__am_type_color))    ;
}
void __am_check_type(void* __am_v) {
if (__amber_rt_is_type(__am_v, &__am_type_color)    ) {
        {
__amber_rt_println(__amber_rt_box_string(__amber_rt_str_concat("Received a color: ", __amber_rt_to_string(__am_v))))            ;
        }
    }
}
int __am_is_color_blue(int __am_c) {
return (__am_c == __am_color_blue)    ;
}
int main(int argc, char** argv) {
    GC_INIT();
    const char* __am_variants_color[] = { "red", "green", "blue" };
    typedef enum {
        __am_color_red,
        __am_color_green,
        __am_color_blue
    } __am_color;
    __amber_type_t __am_type_color = { "color", 94842823, __am_variants_color, 3 };
__am_main()    ;
    return 0;
}
