package off.kys.amber_lang.transpiler.codegen

import off.kys.amber_lang.runtime.RuntimeProvider
import off.kys.amber_lang.transpiler.ast.ArrayLiteralExpression
import off.kys.amber_lang.transpiler.ast.AssignmentExpression
import off.kys.amber_lang.transpiler.ast.AstNode
import off.kys.amber_lang.transpiler.ast.BinaryExpression
import off.kys.amber_lang.transpiler.ast.BlockStatement
import off.kys.amber_lang.transpiler.ast.CallExpression
import off.kys.amber_lang.transpiler.ast.CatchExpression
import off.kys.amber_lang.transpiler.ast.ErrorNode
import off.kys.amber_lang.transpiler.ast.Expression
import off.kys.amber_lang.transpiler.ast.ExpressionStatement
import off.kys.amber_lang.transpiler.ast.FunctionDeclaration
import off.kys.amber_lang.transpiler.ast.IdentifierExpression
import off.kys.amber_lang.transpiler.ast.IfStatement
import off.kys.amber_lang.transpiler.ast.ImportStatement
import off.kys.amber_lang.transpiler.ast.IndexAccessExpression
import off.kys.amber_lang.transpiler.ast.IsExpression
import off.kys.amber_lang.transpiler.ast.LiteralExpression
import off.kys.amber_lang.transpiler.ast.MemberAccessExpression
import off.kys.amber_lang.transpiler.ast.PanicExpression
import off.kys.amber_lang.transpiler.ast.Program
import off.kys.amber_lang.transpiler.ast.ReturnStatement
import off.kys.amber_lang.transpiler.ast.UnaryExpression
import off.kys.amber_lang.transpiler.ast.VariableDeclaration
import off.kys.amber_lang.transpiler.ast.WhileStatement
import off.kys.amber_lang.transpiler.type.Symbol
import off.kys.amber_lang.transpiler.type.Type
import off.kys.amber_lang.transpiler.type.Type.StringType

class BashCodeGenerator(
    private val expressionTypes: Map<Expression, Type>,
    private val resolvedSymbols: Map<Expression, Symbol>,
    private val importedModulePrograms: Map<String, Program>,
    private val usedSymbolsByModule: Map<String, Set<String>>,
    private val runtimeProvider: RuntimeProvider
) : AstNodeVisitor<Unit> {

    private var output = StringBuilder()

    // Recreated on every generate() call so both the temp-var counter and the
    // per-compilation salt reset along with everything else.
    private lateinit var names: BashNamespace

    private var currentModuleNamespace: String? = null
    private var indentLevel = 0
    private var inFunction = false
    private var currentFunctionName: String? = null
    private var currentFunctionReturnType: Type? = null

    private val includedModules = mutableSetOf<String>()
    private val usedIntrinsics = mutableSetOf<String>()

    private fun mangleName(name: String): String {
        val base = currentModuleNamespace ?: names.userPrefix
        return "$base$name"
    }

    private fun nextTempVar(): String = names.nextTemp()

    private fun indent() {
        output.append("    ".repeat(indentLevel))
    }

    private fun declareAndAssign(name: String, value: String, isReadonly: Boolean = false) {
        indent()
        if (inFunction) {
            output.append("local $name\n")
            indent()
            output.append("$name=$value\n")
        } else {
            if (isReadonly) {
                output.append("readonly $name=$value\n")
            } else {
                output.append("$name=$value\n")
            }
        }
    }

    private fun visitAstNode(node: AstNode) {
        when (node) {
            is Program -> visitProgram(node)
            is BlockStatement -> visitBlockStatement(node)
            is VariableDeclaration -> visitVariableDeclaration(node)
            is ExpressionStatement -> visitExpressionStatement(node)
            is IfStatement -> visitIfStatement(node)
            is WhileStatement -> visitWhileStatement(node)
            is FunctionDeclaration -> visitFunctionDeclaration(node)
            is ReturnStatement -> visitReturnStatement(node)
            is ImportStatement -> visitImportStatement(node)
            is LiteralExpression, is IdentifierExpression, is BinaryExpression,
            is UnaryExpression, is CallExpression, is AssignmentExpression,
            is MemberAccessExpression, is IsExpression, is ArrayLiteralExpression,
            is IndexAccessExpression, is PanicExpression, is CatchExpression
                -> resolveExpression(node)

            is ErrorNode -> visitErrorNode(node)
            else -> throw NotImplementedError("visiting ${node::class.simpleName?.lowercase()} not implemented")
        }
    }

    fun generate(program: Program): String {
        output.setLength(0)
        includedModules.clear()
        usedIntrinsics.clear()
        names = BashNamespace()
        currentFunctionName = null
        currentModuleNamespace = null

        val mainBody = StringBuilder()
        val originalOutput = output
        output = mainBody

        visitProgram(program)

        output = originalOutput
        output.append("#!/bin/bash\n# generated by amber transpiler\nset -e\n\n")
        output.append(runtimeProvider.getRuntimeSource(names.runtimePrefix, usedIntrinsics))
        output.append(mainBody)
        return output.toString()
    }

    private val returnTargets = mutableListOf<String>()

    private fun resolveExpression(node: AstNode): String {
        return when (node) {
            is LiteralExpression -> {
                when (val value = node.value) {
                    is String -> "${ValueTag.STR}:$value"
                    is Char -> "${ValueTag.CHAR}:$value"
                    is Boolean -> if (value) "${ValueTag.BOOL}:0" else "${ValueTag.BOOL}:1"
                    null -> "${ValueTag.UNIT}:"
                    else -> "${ValueTag.NUM}:$value"
                }
            }

            is IdentifierExpression -> {
                val symbol = resolvedSymbols[node]
                if (symbol?.isIntrinsic == true) {
                    val platformName = runtimeProvider.getPlatformName(node.name)
                    if (platformName != null) {
                        if (runtimeProvider.isRuntimeHelper(node.name)) "${names.runtimePrefix}$platformName" else platformName
                    } else {
                        mangleName(node.name)
                    }
                } else {
                    mangleName(node.name)
                }
            }

            is MemberAccessExpression -> {
                flattenMemberAccess(node)
            }

            is CallExpression -> {
                val symbol = resolvedSymbols[node.callee]
                val name = if (symbol?.isIntrinsic == true) {
                    val platformName = runtimeProvider.getPlatformName(symbol.name)
                    if (platformName != null) {
                        if (runtimeProvider.isRuntimeHelper(symbol.name)) "${names.runtimePrefix}$platformName" else platformName
                    } else {
                        mangleName(symbol.name)
                    }
                } else {
                    when (val callee = node.callee) {
                        is IdentifierExpression -> mangleName(callee.name)
                        is MemberAccessExpression -> flattenMemberAccess(callee)
                        else -> throw NotImplementedError("dynamic dispatch not supported in bash target")
                    }
                }

                if (symbol?.isIntrinsic == true) {
                    usedIntrinsics.add(symbol.name)
                    val platformName = runtimeProvider.getPlatformName(symbol.name)
                    if (platformName != null) {
                        val isHelper = runtimeProvider.isRuntimeHelper(symbol.name)
                        val finalPlatformName = if (isHelper) "${names.runtimePrefix}$platformName" else platformName

                        val resolvedArgs = node.arguments.map { arg ->
                            val argStr = resolveExpression(arg)
                            val argRef = formatRef(argStr)
                            val platformToString = runtimeProvider.getPlatformName("to_string") ?: "to_string"
                            usedIntrinsics.add("to_string")
                            val mangledToString = "${names.runtimePrefix}$platformToString"
                            if (finalPlatformName.startsWith("echo")) "\"\$($mangledToString \"\$${argRef}\")\"" else "\"$${argRef}\""
                        }

                        val argsStr = resolvedArgs.joinToString("") { " $it" }
                        val returnType = (symbol.type as? Type.FunctionType)?.returnType
                        return if (returnType != null && returnType != Type.UnitType) {
                            val tmp = nextTempVar()
                            val tag = when (returnType) {
                                is Type.NumberType -> ValueTag.NUM
                                is Type.StringType -> ValueTag.STR
                                is Type.BooleanType -> ValueTag.BOOL
                                is Type.CharType -> ValueTag.CHAR
                                is Type.ListType -> ValueTag.ARR
                                is Type.ArrayListType -> ValueTag.ARR
                                is Type.UnsafeType -> null
                                else -> ValueTag.UNIT
                            }
                            if (tag != null) {
                                declareAndAssign(tmp, "\"$tag:\$($finalPlatformName$argsStr)\"")
                            } else {
                                declareAndAssign(tmp, "\"\$($finalPlatformName$argsStr)\"")
                            }
                            tmp
                        } else {
                            indent()
                            output.append("$finalPlatformName$argsStr\n")
                            "${ValueTag.UNIT}:"
                        }
                    }
                }

                val resolvedArgs = node.arguments.map { arg ->
                    val argStr = resolveExpression(arg)
                    val argRef = formatRef(argStr)
                    val platformToString = runtimeProvider.getPlatformName("to_string") ?: "to_string"
                    usedIntrinsics.add("to_string")
                    val mangledToString = "${names.runtimePrefix}$platformToString"
                    if (name == "echo") "\"\$($mangledToString \"\$${argRef}\")\"" else "\"$${argRef}\""
                }

                val argsStr = resolvedArgs.joinToString("") { " $it" }
                indent()
                output.append("$name$argsStr\n")

                val isBuiltIn =
                    (node.callee is IdentifierExpression && runtimeProvider.getBuiltInNames().contains(node.callee.name)) || name == "echo"

                if (isBuiltIn) {
                    "${ValueTag.UNIT}:"
                } else {
                    val callTempVar = nextTempVar()
                    declareAndAssign(callTempVar, "\"\$${names.returnPrefix}${name}\"")
                    callTempVar
                }
            }

            is BinaryExpression -> {
                val leftType = expressionTypes[node.left]
                val rightType = expressionTypes[node.right]
                val leftStr = resolveExpression(node.left)
                val leftRef = formatRef(leftStr)
                val rightStr = resolveExpression(node.right)
                val rightRef = formatRef(rightStr)

                val l = "\${${leftRef}#*:}"
                val r = "\${${rightRef}#*:}"

                val tmp = nextTempVar()

                when (node.operator) {
                    "+" -> {
                        if (leftType is Type.ArrayListType) {
                            val arrayNameVar = nextTempVar()
                            declareAndAssign(arrayNameVar, l)
                            indent()
                            output.append("eval \"\${$arrayNameVar}+=(\\\"\$${rightRef}\\\")\"\n")
                            return l
                        } else if (leftType == StringType || rightType == StringType) {
                            val platformToString = runtimeProvider.getPlatformName("to_string") ?: "to_string"
                            usedIntrinsics.add("to_string")
                            val mangledToString = "${names.runtimePrefix}$platformToString"
                            val lVal = if (leftType == StringType) l else "\$($mangledToString \"\$${leftRef}\")"
                            val rVal = if (rightType == StringType) r else "\$($mangledToString \"\$${rightRef}\")"
                            declareAndAssign(tmp, "\"${ValueTag.STR}:$lVal$rVal\"")
                        } else {
                            declareAndAssign(tmp, "\"${ValueTag.NUM}:\$(echo \"$l + $r\" | bc -l)\"")
                        }
                    }

                    "-", "*", "/", "%" -> declareAndAssign(tmp, "\"${ValueTag.NUM}:\$(echo \"$l ${node.operator} $r\" | bc -l)\"")
                    "==", "!=", "<", ">", "<=", ">=" -> declareAndAssign(tmp, "\"${ValueTag.BOOL}:\$( (( \$(echo \"$l ${node.operator} $r\" | bc -l) )) && echo 0 || echo 1 )\"")
                    "&&", "||" -> declareAndAssign(tmp, "\"${ValueTag.BOOL}:\$( [[ $l -eq 0 ${node.operator} $r -eq 0 ]] && echo 0 || echo 1 )\"")
                    else -> throw NotImplementedError("operator ${node.operator} not implemented")
                }
                tmp
            }

            is UnaryExpression -> {
                val operandStr = resolveExpression(node.operand)
                val operandRef = formatRef(operandStr)
                val v = "\${${operandRef}#*:}"
                val tmp = nextTempVar()
                when (node.operator) {
                    "-" -> {
                        declareAndAssign(tmp, "\"${ValueTag.NUM}:\$(echo \"-1 * $v\" | bc -l)\"")
                        tmp
                    }
                    "!" -> {
                        declareAndAssign(tmp, "\"${ValueTag.BOOL}:\$( [ $v -ne 0 ] && echo 0 || echo 1 )\"")
                        tmp
                    }
                    else -> operandStr
                }
            }

            is IsExpression -> {
                val valStr = resolveExpression(node.left)
                val valRef = formatRef(valStr)
                val tag = when (node.typeName) {
                    "number", "num", "Int" -> ValueTag.NUM
                    "string", "str" -> ValueTag.STR
                    "boolean", "bool" -> ValueTag.BOOL
                    "char" -> ValueTag.CHAR
                    "unit" -> ValueTag.UNIT
                    "array_list", "list" -> ValueTag.ARR
                    else -> "unknown"
                }
                val tmp = nextTempVar()
                declareAndAssign(tmp, "\"${ValueTag.BOOL}:\$( [[ \"\$${valRef}\" == $tag:* ]] && echo 0 || echo 1 )\"")
                tmp
            }

            is ArrayLiteralExpression -> {
                val tmp = nextTempVar()
                val elementsStr = node.elements.joinToString(" ") { "\"\$${formatRef(resolveExpression(it))}\"" }
                indent()
                output.append("declare -g -a $tmp=($elementsStr)\n")
                "${ValueTag.ARR}:$tmp"
            }

            is IndexAccessExpression -> {
                val targetStr = resolveExpression(node.target)
                val targetRef = formatRef(targetStr)
                val indexStr = resolveExpression(node.index)
                val indexRef = formatRef(indexStr)
                val i = "\${${indexRef}#*:}"
                val tmp = nextTempVar()

                val targetType = expressionTypes[node.target]
                if (targetType == StringType) {
                    val v = "\${${targetRef}#*:}"
                    declareAndAssign(tmp, "\"${ValueTag.CHAR}:\${$v:$i:1}\"")
                } else {
                    val arrayNameStr = "\${${targetRef}#*:}"
                    val idx = "\$(printf \"%.0f\" \"\${${indexRef}#*:}\")"
                    // Correctly escape for Bash eval: we want $(eval echo "${$array_name[$index]}")
                    val code = "\"\$(eval echo \\\"\\\${${arrayNameStr}[${idx}]}\\\")\""
                    declareAndAssign(tmp, code)
                }
                tmp
            }

            is AssignmentExpression -> {
                val valStr = resolveExpression(node.value)
                val valRef = formatRef(valStr)
                indent()
                output.append("${mangleName(node.target.name)}=\"\$${valRef}\"\n")
                mangleName(node.target.name)
            }

            is PanicExpression -> {
                val messageStr = if (node.message != null) {
                    val msgStr = resolveExpression(node.message)
                    "\${${formatRef(msgStr)}#*:}"
                } else {
                    "script panicked"
                }

                val isUnsafeFunction = currentFunctionReturnType is Type.UnsafeType
                if (node.isFatal || !isUnsafeFunction) {
                    indent()
                    output.append("echo \"$messageStr\" >&2\n")
                    indent()
                    output.append("exit 1\n")
                } else {
                    val retVar = currentFunctionName?.let { "${names.returnPrefix}$it" } ?: "${names.returnPrefix}val"
                    indent()
                    output.append("$retVar=\"${ValueTag.ERR}:$messageStr\"\n")
                    indent()
                    output.append("return 0\n")
                }
                "${ValueTag.UNIT}:"
            }

            is CatchExpression -> {
                val targetStr = resolveExpression(node.target)
                val targetRef = formatRef(targetStr)
                val tmp = nextTempVar()
                returnTargets.add(tmp)

                indent()
                output.append("if [[ \"\$${targetRef}\" == ${ValueTag.ERR}:* ]]; then\n")
                indentLevel++

                val errorVarName = mangleName(node.errorVarName)
                indent()
                output.append("$errorVarName=\"\${${targetRef}#*:}\"\n")

                node.body.statements.forEach { visitAstNode(it) }

                val lastStatement = node.body.statements.lastOrNull()
                if (lastStatement is ExpressionStatement) {
                    val lastExprStr = resolveExpression(lastStatement.expression)
                    indent()
                    output.append("$tmp=\"\$${formatRef(lastExprStr)}\"\n")
                } else if (lastStatement !is ReturnStatement) {
                    indent()
                    output.append("$tmp=\"${ValueTag.UNIT}:\"\n")
                }

                indentLevel--
                indent()
                output.append("else\n")
                indentLevel++

                indent()
                output.append("$tmp=\"\$${targetRef}\"\n")

                indentLevel--
                indent()
                output.append("fi\n")

                returnTargets.removeAt(returnTargets.size - 1)
                tmp
            }

            is ErrorNode -> visitErrorNode(node)

            else -> throw IllegalArgumentException("Not a valid expression node: ${node::class.simpleName}")
        }
    }

    private fun formatRef(ref: String): String {
        return if (ref.startsWith(names.root)) ref else {
            val tmp = nextTempVar()
            declareAndAssign(tmp, "\"$ref\"")
            tmp
        }
    }

    override fun visitImportStatement(stmt: ImportStatement) {
        val path = stmt.path
        val usedSet = usedSymbolsByModule[path] ?: return
        if (usedSet.isEmpty()) return

        val moduleAST = importedModulePrograms[path]
        if (moduleAST != null && !includedModules.contains(path)) {
            includedModules.add(path)
            val alias = stmt.asName?.name ?: path.split(":").last().substringBeforeLast(".amb")
            val oldNamespace = currentModuleNamespace
            currentModuleNamespace = names.moduleNamespace(alias)

            output.append("\n# --- module: $alias ($path) ---\n")
            moduleAST.statements.forEach { node ->
                val name = when (node) {
                    is VariableDeclaration -> node.name.name
                    is FunctionDeclaration -> node.name.name
                    else -> null
                }
                if (name == null || usedSet.contains(name)) visitAstNode(node)
            }
            output.append("# --- end module: $alias ---\n\n")
            currentModuleNamespace = oldNamespace
        }
    }

    override fun visitProgram(program: Program) = program.statements.forEach { visitAstNode(it) }
    override fun visitBlockStatement(block: BlockStatement) = block.statements.forEach { visitAstNode(it) }

    override fun visitVariableDeclaration(declaration: VariableDeclaration) {
        val name = mangleName(declaration.name.name)
        val valStr = declaration.initializer?.let { resolveExpression(it) } ?: "${ValueTag.UNIT}:"
        val valRef = formatRef(valStr)
        declareAndAssign(name, "\"\$${valRef}\"", !declaration.isMutable)
    }

    override fun visitExpressionStatement(statement: ExpressionStatement) {
        resolveExpression(statement.expression)
    }

    override fun visitIfStatement(stmt: IfStatement) {
        val condStr = resolveExpression(stmt.condition)
        val condRef = formatRef(condStr)
        indent(); output.append("if [ \"\${${condRef}#*:}\" -eq 0 ]; then\n")
        indentLevel++; visitBlockStatement(stmt.thenBranch); indentLevel--
        stmt.elseBranch?.let {
            indent(); output.append("else\n")
            indentLevel++; visitBlockStatement(it); indentLevel--
        }
        indent(); output.append("fi\n")
    }

    override fun visitWhileStatement(stmt: WhileStatement) {
        val condStr = resolveExpression(stmt.condition)
        val condRef = formatRef(condStr)
        indent(); output.append("while [ \"\${${condRef}#*:}\" -eq 0 ]; do\n")
        indentLevel++; visitBlockStatement(stmt.body); indentLevel--
        indent(); output.append("done\n")
    }

    override fun visitFunctionDeclaration(func: FunctionDeclaration) {
        if (func.isIntrinsic) return

        val prevInFunc = inFunction
        val prevFuncName = currentFunctionName
        val prevFuncReturnType = currentFunctionReturnType

        inFunction = true
        val mangledName = mangleName(func.name.name)
        currentFunctionName = mangledName
        
        // Use a recursive lookup to find the function type
        fun findFuncType(expr: Expression): Type? {
            return expressionTypes[expr] ?: resolvedSymbols[expr]?.type
        }
        
        val funcType = findFuncType(func.name)
        currentFunctionReturnType = (funcType as? Type.FunctionType)?.returnType ?: (func.returnTypeAnnotation?.let { 
             off.kys.amber_lang.transpiler.type.TypeResolver { _, _, _ -> }.resolveType(it, func)
        })

        indent(); output.append("$mangledName() {\n")
        indentLevel++
        func.parameters.forEachIndexed { i, p ->
            val name = mangleName(p.name.name)
            val defaultStr = p.defaultValue?.let { resolveExpression(it) } ?: "${ValueTag.UNIT}:"
            val defaultRef = formatRef(defaultStr)
            declareAndAssign(name, "\"\${${i + 1}:-\$${defaultRef}}\"")
        }
        func.body?.let {
            visitBlockStatement(it)
            // Handle implicit return for single-expression functions
            if (it.statements.size == 1 && it.statements[0] is ExpressionStatement && currentFunctionReturnType != Type.UnitType) {
                val exprStmt = it.statements[0] as ExpressionStatement
                val valStr = resolveExpression(exprStmt.expression)
                val retVar = currentFunctionName?.let { name -> "${names.returnPrefix}$name" } ?: "${names.returnPrefix}val"
                indent()
                output.append("$retVar=\"\$${formatRef(valStr)}\"\n")
            }
        }
        indentLevel--
        indent(); output.append("}\n\n")

        // Reset current function name to avoid accidental return prefixing outside
        currentFunctionName = prevFuncName
        currentFunctionReturnType = prevFuncReturnType
        inFunction = prevInFunc
    }

    override fun visitReturnStatement(stmt: ReturnStatement) {
        val retVar = returnTargets.lastOrNull() ?: (currentFunctionName?.let { "${names.returnPrefix}$it" } ?: "${names.returnPrefix}val")
        stmt.value?.let { valueNode ->
            val valStr = resolveExpression(valueNode)
            val valRef = formatRef(valStr)
            indent()
            output.append("$retVar=\"\$${valRef}\"\n")
        } ?: run {
            // If it's a bare return, ensure we don't carry over old return values
            indent()
            output.append("$retVar=\"${ValueTag.UNIT}:\"\n")
        }
        
        // Only emit Bash return if we are returning from a function, not a block
        if (returnTargets.isEmpty()) {
            indent()
            output.append("return 0\n")
        }
    }

    private fun flattenMemberAccess(expr: MemberAccessExpression): String {
        val target = when (val t = expr.target) {
            is IdentifierExpression -> {
                val symbol = resolvedSymbols[t]
                if (symbol?.type is Type.ModuleType) {
                    names.moduleNamespace(t.name)
                } else {
                    "${names.userPrefix}${t.name}"
                }
            }
            is MemberAccessExpression -> flattenMemberAccess(t)
            else -> throw IllegalStateException("invalid member access target: ${expr.target::class.simpleName?.lowercase()}")
        }
        return "${target}${expr.member.name}"
    }

    override fun visitErrorNode(errorNode: ErrorNode) =
        throw IllegalStateException("codegen aborted: ${errorNode.message.lowercase()}")

    override fun visitLiteralExpression(literal: LiteralExpression) {
        output.append(resolveExpression(literal))
    }

    override fun visitIdentifierExpression(identifier: IdentifierExpression) {
        output.append(resolveExpression(identifier))
    }

    override fun visitBinaryExpression(expr: BinaryExpression) {
        output.append(resolveExpression(expr))
    }

    override fun visitUnaryExpression(expr: UnaryExpression) {
        output.append(resolveExpression(expr))
    }

    override fun visitAssignmentExpression(expr: AssignmentExpression) {
        output.append(resolveExpression(expr))
    }

    override fun visitCallExpression(call: CallExpression) {
        resolveExpression(call)
    }

    override fun visitMemberAccessExpression(expr: MemberAccessExpression) {
        output.append(resolveExpression(expr))
    }

    override fun visitPanicExpression(expr: PanicExpression) {
        resolveExpression(expr)
    }

    override fun visitCatchExpression(expr: CatchExpression) {
        resolveExpression(expr)
    }
}