package off.kys.amber_lang.transpiler.codegen

import kotlin.random.Random

/**
 * Owns every reserved Bash identifier the generator emits: user-variable mangling,
 * compiler temporaries, function return slots, module namespacing, and runtime
 * helper names.
 *
 * All *internal* namespaces (temporaries, return slots, runtime helpers, module
 * containers) are salted with a value generated fresh for each [BashCodeGenerator.generate]
 * call. Amber source is compiled with no knowledge of that salt, so nothing a user
 * writes -- however they name their variables, functions, or module aliases -- can
 * accidentally (or deliberately) collide with a name the generator depends on
 * internally. Only [userPrefix] is unsalted, since user identifiers are always
 * namespaced *under* it rather than generated by us, so there's nothing for it to
 * collide with.
 */
class BashNamespace {
    private val salt = generateSalt()
    private var tempCounter = 0

    /** Common root every reserved name lives under, so callers can cheaply test
     *  "is this string a Bash variable reference at all" (see [BashCodeGenerator.formatRef]). */
    val root = "__amber_"

    /** Prefix for mangled user-declared identifiers (variables, functions). Unsalted. */
    val userPrefix = root

    /** Prefix for compiler-generated temporaries. Salted -- see class doc. */
    val tempPrefix = "${root}tmp${salt}_"

    /** Prefix for a function's return-value slot. Salted -- see class doc. */
    val returnPrefix = "${root}ret${salt}_"

    /** Prefix for runtime helper functions injected by [off.kys.amber_lang.runtime.RuntimeProvider]. Salted. */
    val runtimePrefix = "${root}rt${salt}_"

    /** Prefix wrapping an imported module's namespace, before the module's alias. Salted. */
    val modulePrefix = "${root}mod${salt}_"

    fun nextTemp(): String = "$tempPrefix${tempCounter++}"

    fun moduleNamespace(alias: String): String = "$modulePrefix${alias}_"

    private fun generateSalt(): String {
        val n = Random.nextLong().let { if (it < 0) -it else it }
        return "_" + n.toString(36).padStart(8, '0')
    }
}
