package amber.compiler.backend.c

import amber.compiler.CompilerConfig
import amber.compiler.ast.Expression
import amber.compiler.ast.FunctionDeclaration
import amber.compiler.ast.Program
import amber.compiler.ast.VariableDeclaration
import amber.compiler.backend.Backend
import amber.compiler.symbol.Symbol
import amber.compiler.type.Type
import amber.runtime.BoehmGC
import amber.runtime.GarbageCollector
import amber.runtime.RuntimeProvider

class CBackend(
    private val expressionTypes: Map<Expression, Type>,
    private val resolvedSymbols: Map<Expression, Symbol>,
    private val resolvedIsTypes: Map<amber.compiler.ast.IsExpression, Type> = emptyMap(),
    private val runtimeProvider: RuntimeProvider,
    private val gc: GarbageCollector = BoehmGC,
    private val config: CompilerConfig? = null
) : Backend {

    override fun generate(
        program: Program,
        expressionTypes: Map<Expression, Type>,
        resolvedSymbols: Map<Expression, Symbol>
    ): String {
        val writer = CodeWriter()
        
        // Use provided maps or fall back to class members
        val usedExpressionTypes = expressionTypes.ifEmpty { this.expressionTypes }
        val usedResolvedSymbols = resolvedSymbols.ifEmpty { this.resolvedSymbols }

        if (config != null) {
            writer.writeLine("/*")
            writer.writeLine(" * Generated by Amber Compiler")
            writer.writeLine(" * Entry: ${config.entryFile}")
            writer.writeLine(" * Optimization: ${config.optimizationLevel}")
            writer.writeLine(" * GC: ${config.gc}")
            writer.writeLine(" */")
            writer.writeLine("")
        }

        val symbolEmitter = SymbolEmitter()
        val typeMapper = CTypeMapper()
        val runtimeEmitter = RuntimeEmitter(writer, gc)
        val expressionEmitter = ExpressionEmitter(writer, usedExpressionTypes, usedResolvedSymbols, resolvedIsTypes, symbolEmitter, runtimeProvider)
        val statementEmitter = StatementEmitter(writer, expressionEmitter, symbolEmitter, typeMapper, usedExpressionTypes, usedResolvedSymbols)

        runtimeEmitter.emitHeaders()
        runtimeEmitter.emitTypedefs()
        runtimeEmitter.emitIntrinsics()
        runtimeEmitter.emitDefinitions()

        val functions = program.statements.filterIsInstance<FunctionDeclaration>().filter { !it.isIntrinsic }
        val variables = program.statements.filterIsInstance<VariableDeclaration>().filter { !it.isIntrinsic }

        variables.forEach { statementEmitter.emit(it, declarationOnly = true, isTopLevel = true) }
        functions.forEach { statementEmitter.emit(it, declarationOnly = true) }
        writer.writeLine("")
        functions.forEach { statementEmitter.emit(it) }

        writer.writeLine("int main(int argc, char** argv) {")
        writer.indent()
        if (gc.initCall.isNotEmpty()) {
            writer.writeLine(gc.initCall)
        }
        
        program.statements.forEach { stmt ->
            when (stmt) {
                is VariableDeclaration -> if (!stmt.isIntrinsic) statementEmitter.emit(stmt, isTopLevel = true)
                is FunctionDeclaration -> {}
                else -> statementEmitter.emit(stmt)
            }
        }
        
        writer.writeLine("return 0;")
        writer.dedent()
        writer.writeLine("}")

        return writer.toString()
    }
    
    fun generate(program: Program): String = generate(program, expressionTypes, resolvedSymbols)
}
