package amber.compiler.backend.c

import amber.compiler.CompilerConfig
import amber.compiler.ast.EnumDeclaration
import amber.compiler.ast.Expression
import amber.compiler.ast.ExtensionDeclaration
import amber.compiler.ast.FunctionDeclaration
import amber.compiler.ast.Program
import amber.compiler.ast.StructDeclaration
import amber.compiler.ast.VariableDeclaration
import amber.compiler.backend.Backend
import amber.compiler.symbol.Symbol
import amber.compiler.type.Type
import amber.runtime.BoehmGC
import amber.runtime.GarbageCollector
import amber.runtime.RuntimeProvider

class CBackend(
    private val expressionTypes: Map<Expression, Type>,
    private val resolvedSymbols: Map<Expression, Symbol>,
    private val resolvedIsTypes: Map<amber.compiler.ast.IsExpression, Type> = emptyMap(),
    private val importedModulePrograms: Map<String, Program> = emptyMap(),
    private val runtimeProvider: RuntimeProvider,
    private val gc: GarbageCollector = BoehmGC,
    private val config: CompilerConfig? = null
) : Backend {

    override fun generate(
        program: Program,
        expressionTypes: Map<Expression, Type>,
        resolvedSymbols: Map<Expression, Symbol>
    ): String {
        val writer = CodeWriter()
        
        // Use provided maps or fall back to class members
        val usedExpressionTypes = expressionTypes.ifEmpty { this.expressionTypes }
        val usedResolvedSymbols = resolvedSymbols.ifEmpty { this.resolvedSymbols }

        if (config != null) {
            writer.writeLine("/*")
            writer.writeLine(" * Generated by Amber Compiler")
            writer.writeLine(" * Entry: ${config.entryFile}")
            writer.writeLine(" * Optimization: ${config.optimizationLevel}")
            writer.writeLine(" * GC: ${config.gc}")
            writer.writeLine(" */")
            writer.writeLine("")
        }

        val symbolEmitter = SymbolEmitter()
        val typeMapper = CTypeMapper(symbolEmitter)
        
        val context = CGenerationContext(
            writer,
            usedExpressionTypes,
            usedResolvedSymbols,
            resolvedIsTypes,
            symbolEmitter,
            typeMapper,
            runtimeProvider
        )

        val runtimeEmitter = RuntimeEmitter(writer, gc)
        val expressionEmitter = ExpressionEmitter(context)
        val statementEmitter = StatementEmitter(context, expressionEmitter)
        expressionEmitter.statementEmitter = statementEmitter

        val allPrograms = listOf(program) + importedModulePrograms.values

        val usedSymbols = usedResolvedSymbols.values.toSet()
        val usedIntrinsicNames = usedSymbols.filter { it.isIntrinsic }.map { it.qualifiedName }.toMutableSet()
        
        // Always include basic runtime helpers
        usedIntrinsicNames.add("std.runtime.panic")
        usedIntrinsicNames.add("std.str.from_num")
        usedIntrinsicNames.add("std.str.str_concat")
        usedIntrinsicNames.add("std.runtime.to_string")

        runtimeEmitter.emitHeaders()
        runtimeEmitter.emitTypedefs()
        runtimeEmitter.emitIntrinsics()
        runtimeEmitter.emitIntrinsicImplementations(usedIntrinsicNames)
        runtimeEmitter.emitDefinitions()

        val enums = allPrograms.flatMap { it.statements.filterIsInstance<EnumDeclaration>() }
        val structs = allPrograms.flatMap { it.statements.filterIsInstance<StructDeclaration>() }
        val extensions = allPrograms.flatMap { it.statements.filterIsInstance<ExtensionDeclaration>() }
        val functions = allPrograms.flatMap { it.statements.filterIsInstance<FunctionDeclaration>() }.filter { !it.isIntrinsic }
        val variables = allPrograms.flatMap { it.statements.filterIsInstance<VariableDeclaration>() }.filter { !it.isIntrinsic }

        val allFunctions = extensions.flatMap { it.functions }.filter { !it.isIntrinsic && (usedResolvedSymbols[it.name]?.isUsed == true) } +
                functions.filter { usedResolvedSymbols[it.name]?.isUsed == true || it in program.statements }

        enums.forEach { statementEmitter.emit(it) }
        structs.forEach { statementEmitter.emit(it) }
        variables.forEach { statementEmitter.emit(it, declarationOnly = true, isTopLevel = true) }
        allFunctions.forEach { statementEmitter.emit(it, declarationOnly = true) }
        writer.writeLine("")
        allFunctions.forEach { statementEmitter.emit(it) }

        writer.writeLine("int main(int argc, char** argv) {")
        writer.indent()
        if (gc.initCall.isNotEmpty()) {
            writer.writeLine(gc.initCall)
        }
        
        program.statements.forEach { stmt ->
            when (stmt) {
                is VariableDeclaration -> if (!stmt.isIntrinsic) statementEmitter.emit(stmt, isTopLevel = true)
                is FunctionDeclaration -> {}
                is EnumDeclaration -> {}
                is StructDeclaration -> {}
                else -> statementEmitter.emit(stmt)
            }
        }
        
        writer.writeLine("return 0;")
        writer.dedent()
        writer.writeLine("}")

        return writer.toString()
    }
    
    fun generate(program: Program): String = generate(program, expressionTypes, resolvedSymbols)
}
